### ISSUE TITLE
Crystal heart from the artifacts mod doesn't give additional health

### ISSUE THREAD

**Issue by nullAdept** [Ladysnake/Requiem#568] opened 2022-08-09 22:17 UTC
### Mods&versions
https://www.curseforge.com/minecraft/mc-mods/artifacts 1.18
Requiem 2.0.0 beta 9 
### Compatibility issue
it doesn't :(

**Comment by Pyrofab** [comment] 2022-08-10 13:31
Alright it was easy enough to find, but for next time could you please link to the conflicting mod and note the versions (Minecraft, Requiem, conflicting mod) that you used ?

**Comment by nullAdept** [comment] 2022-08-10 17:55
will do, will fix

**Comment by PsychoBreadstick** [comment] 2023-03-05 20:46
Duplicate of https://github.com/Ladysnake/Requiem/issues/326

**Closed as completed by PsychoBreadstick** 2023-03-05 20:46 UTC
Labels: bug, duplicate, mod interaction, t:confirmed
