### ISSUE TITLE
[Bug] Pehkui attributes persist after leaving a player shell

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#566] opened 2022-08-08 08:16 UTC
The following applies when Pehkui 3.4.0 and Requiem 2.0.0-beta.12 are installed on Minecraft 1.19.

## Bug
After leaving a shell, your Pehkui stats like `pehkui:height` remain attached to your soul, and apply to newly-possessed mobs. The only way to reset these stats are by possessing another player shell, using `/scale reset`, or by using `/kill` in soul mode.

For now, you can work around this by running `/scale reset` on all vagrant players every tick. This works because the player's stats are correctly reset after creating or possessing a player shell anyway.

## Expected behavior
After leaving a player shell through death or dissociation, your Pehkui stats should reset.

**Comment by PsychoBreadstick** [comment] 2023-03-05 20:52
Duplicate of https://github.com/Ladysnake/Requiem/issues/468

**Closed as completed by PsychoBreadstick** 2023-03-05 20:52 UTC
Labels: bug, mod interaction, t:confirmed
