### ISSUE TITLE
Chicken Flying

### ISSUE THREAD

**Issue by KingMushroomBoy** [Ladysnake/Requiem#531] opened 2022-06-25 22:37 UTC
When are you going to fix this?
It might be another mod or something that is causing it?
I also found another bug. Riding as a baby zombie on a chicken glitches the zombie and makes it go inside the chicken.
This also applies to possessing a baby strider on a normal strider.

**Comment by Pyrofab** [comment] 2022-07-15 13:11
Duplicate of #439

**Closed as completed by Pyrofab** 2022-07-15 13:11 UTC
