### ISSUE TITLE
Pandemonium Multiplayer Bug

### ISSUE THREAD

**Issue by mariotime1287** [Ladysnake/Requiem#188] opened 2020-08-10 18:20 UTC
Pandemonium's special overlays that apply the "vision" of that mob to you, such as a creeper or spider apply to other players who aren't supposed to have them.

**Comment by Pyrofab** [comment] 2020-11-02 20:24
Duplicate of #180

**Comment by Pyrofab** [comment] 2020-11-28 12:38
Also fixed in d428bce

**Closed by Pyrofab** 2020-11-28 12:38 UTC
Labels: bug
