### ISSUE TITLE
weird mixin issue 

### ISSUE THREAD

**Issue by tiny79971** [Ladysnake/Requiem#604] opened 2022-11-20 12:57 UTC
everytime i try to start micraft with requiem, it crashes on startup, could someone help?
[error.txt](https://github.com/Ladysnake/Requiem/files/10049726/error.txt)

**Comment by Nuzuw1** [comment] 2022-12-14 21:16
Its caused by the new version of the quilt api, but its more or less requiems side problem, 

[Requiem Core](https://github.com/Ladysnake/Requiem) is conflicting with [Quilt Status Effect API](https://github.com/QuiltMC/quilt-standard-libraries).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1309::swapIteratorOperationsPart1 with priority 1000 cannot inject into net/minecraft/class_1309::method_6012()Z merged by org.quiltmc.qsl.entity.effect.mixin.LivingEntityMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.requiem-core.common.json:possession.possessed.PossessableLivingEntityMixin from mod requiem-core -> Prepare Injections ->  -> redirect$cak000$swapIteratorOperationsPart1(Ljava/util/Iterator;)Ljava/lang/Object; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:278)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:153)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:224)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:189)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2378.<clinit>(class_2378.java:207)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

## Game info
Minecraft Version: 1.19.2
Quilt Loader Version: 0.17.8

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

**Comment by PsychoBreadstick** [comment] 2023-03-04 23:14
Seemingly solved in a recent update.

**Closed as completed by PsychoBreadstick** 2023-03-04 23:14 UTC
Labels: bug
