### ISSUE TITLE
Item duplication issue involving cured piglins

### ISSUE THREAD

**Issue by ComradeBlue1337** [Ladysnake/Requiem#431] opened 2021-09-24 17:58 UTC
Happend multiple times but im not sure how to replicate it tho.
However it definetly has to do with rejoining the world.
I had a shield in my offhand and when i rejoined, another shield appeared in my inventory
also pretty sure some other items can duplicate aswell because i remember a sword doing so.

**Comment by Pyrofab** [comment] 2022-07-19 13:55
I believe this happened because of mobs being able to pick up items on their own during possession, which should be fixed in 2.0.0-beta.11. Please open a new issue if you can still reproduce this duplication.

**Closed as completed by Pyrofab** 2022-07-19 13:55 UTC
Labels: bug
