### ISSUE TITLE
Ticking Player crash occuring upon world creation

### ISSUE THREAD

**Issue by sparxy5** [Ladysnake/Requiem#440] opened 2021-10-26 20:21 UTC
Here is the crash log, any help with this would be greatly appreciated.

--- Minecraft Crash Report ----
// You're mean.

Time: 26/10/21 21:09
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.class_1657.handler$zno000$requiem$canClimb(class_1657.java:3476)
	at net.minecraft.class_1309.method_6101(class_1309.java:1420)
	at net.minecraft.class_1309.method_18801(class_1309.java:2169)
	at net.minecraft.class_1309.method_26318(class_1309.java:2144)
	at net.minecraft.class_1309.method_6091(class_1309.java:2098)
	at net.minecraft.class_1657.method_6091(class_1657.java:1568)
	at net.minecraft.class_1309.method_6007(class_1309.java:2547)
	at net.minecraft.class_1657.method_6007(class_1657.java:566)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_3222.method_14226(class_3222.java:434)
	at net.minecraft.class_3244.method_18784(class_3244.java:219)
	at net.minecraft.class_2535.method_10754(class_2535.java:232)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4806/618432863.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1657.handler$zno000$requiem$canClimb(class_1657.java:3476)
	at net.minecraft.class_1309.method_6101(class_1309.java:1420)
	at net.minecraft.class_1309.method_18801(class_1309.java:2169)
	at net.minecraft.class_1309.method_26318(class_1309.java:2144)
	at net.minecraft.class_1309.method_6091(class_1309.java:2098)
	at net.minecraft.class_1657.method_6091(class_1657.java:1568)
	at net.minecraft.class_1309.method_6007(class_1309.java:2547)
	at net.minecraft.class_1657.method_6007(class_1657.java:566)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 300
	Entity Name: Clarkey10
	Entity's Exact location: -193.50, 64.00, 188.50
	Entity's Block location: World: (-194,64,188), Chunk: (at 14,4,12 in -13,11; contains blocks -208,0,176 to -193,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:434)
	at net.minecraft.class_3244.method_18784(class_3244.java:219)
	at net.minecraft.class_2535.method_10754(class_2535.java:232)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4806/618432863.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 891737320 bytes (850 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		chime: Chime 1.1.3
		fabric: Fabric API 0.40.6+1.16
		fabric-api-base: Fabric API Base 0.3.0+f74f7c7d7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+f74f7c7d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+f74f7c7d7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+f74f7c7d7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+f74f7c7d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+f74f7c7d7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+77df1b337d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.4+35ff49a47d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+f74f7c7d7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+f74f7c7d7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+f74f7c7d7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+f74f7c7d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+f74f7c7d7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.5+9385714e7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f74f7c7d7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+f74f7c7d7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4579bd497d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+f74f7c7d7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+f74f7c7d7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+f74f7c7d7d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+9385714e7d
		fabricloader: Fabric Loader 0.12.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		locki: Locki 0.2.1
		minecraft: Minecraft 1.16.5
		playerabilitylib: Pal 1.2.2
		requiem: Requiem 1.7.14
		requiemapi: Requiem-API 1.7.14
		satin: Satin 1.5.1
	Player Count: 1 / 8; [class_3222['Clarkey10'/300, l='ServerLevel[New World]', x=-193.50, y=64.00, z=188.50]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by SettingDust** [comment] 2021-11-06 01:06
Try to use fabric loader 0.11.x

Duplicate https://github.com/Ladysnake/Requiem/issues/436

**Comment by Pyrofab** [comment] 2021-11-12 16:42
Closing as duplicate of #436

**Closed as completed by Pyrofab** 2021-11-12 16:42 UTC
Labels: bug
