### ISSUE TITLE
Mobs Attack After Bumping Into Them While Possessing

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#438] opened 2021-10-24 09:16 UTC
Directly after bumping into a mob while possessing one, all nearby mobs will aggro towards the player. At first I thought this was a glitch with other mods, but after leaving only fabric api and the mod itself in the folder it continues to happen. I do not know if this is intended since I haven't found any documentation on it. If it is intended, "Apologies in advance!"

**Comment by ghost** [comment] 2021-10-24 09:31
A link to gameplay of the possible issue: https://youtu.be/KrD-p0d33Hc

**Comment by Arathain** [comment] 2021-10-24 09:34
"It's not a bug, it's a feature."
basically, intended

**Comment by ghost** [comment] 2021-10-24 09:35
Okay, at least I know now (I shall wait for any developer to close the thread). But besides that, when the mobs keep firing after the player has died already is definitely a bug.

**Comment by Pyrofab** [comment] 2021-11-12 16:46
Which version is that ? In the latest alpha only the mob who you bumped into should aggro, and the firing after death issue should be fixed.

**Comment by ghost** [comment] 2021-11-12 16:50
This was in 2.0.0alpha12. So it Might be outdated, but I can test real quick.

**Comment by Pyrofab** [comment] 2021-11-12 16:51
Yeah, the feature was added in alpha 12 and we got bug reports that were fixed in alpha 13.

**Closed as completed by Pyrofab** 2021-11-12 16:51 UTC
Labels: bug
