### ISSUE TITLE
[0.3.2] SMP client crash when possessing

### ISSUE THREAD

**Issue by vitraiden** [Ladysnake/Requiem#104] opened 2019-01-05 01:59 UTC
Strack trace:

```
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to com.google.common.base.Optional
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.getPossessingEntityId(EntityPossessableImpl.java:101)
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.getPossessingEntity(EntityPossessableImpl.java:107)
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.func_184608_ct(EntityPossessableImpl.java:459)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.func_70071_h_(EntityPossessableImpl.java:154)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Pyrofab** [comment] 2019-01-05 11:43
Oh god, I didn't think I would see that one. It only happens with other mods, right ?

**Comment by Pyrofab** [comment] 2019-01-05 13:13
Confirmed not to happen with only dissolution and a couple other mods. I suspect a mod list mismatch between server and client, or another mod doing something very wrong.

**Comment by vitraiden** [comment] 2019-01-05 17:12
I can't even reproduce it now.  I attempted a process of elimination by starting with Dissolution and slowly adding other mods back in until I was at the full complement.

My theory is that this could have been caused by having some guards from the Minecraft Comes Alive mod following me around when I was cut down by an enderman, although I can't reproduce that either.

**Comment by Pyrofab** [comment] 2019-01-05 17:18
It's normally due to a difference in loading ordee between server and client, a fairly specific issue. I fear it may be hard for me to fix it.

**Comment by vitraiden** [comment] 2019-01-05 17:18
I looked at the crash log a bit more and saw that the entity being ticked is a Stray.  That's very peculiar to me because the crash happened when I tried to possess a Husk (desert zombie) but Strays are the ice biome skeletons.  There isn't a cold biome or even a snowy mountaintop within a thousand blocks of where I was on the server and I was the only player at the time.


```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.getPossessingEntityId(EntityPossessableImpl.java:101)
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.getPossessingEntity(EntityPossessableImpl.java:107)
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.func_184608_ct(EntityPossessableImpl.java:459)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray.func_70071_h_(EntityPossessableImpl.java:154)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: dissolution:minecraft_stray_possessable (ladysnake.dissolution.common.entity.EntityPossessableImpl_EntityStray)
	Entity ID: 24744
	Entity Name: Stray
	Entity's Exact location: -209.50, 68.00, -678.50
	Entity's Block location: World: (-210,68,-679), Chunk: (at 14,4,9 in -14,-43; contains blocks -224,0,-688 to -209,255,-673), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

```

**Comment by Pyrofab** [comment] 2019-01-05 17:19
Oh? Now that's intriguing.

**Comment by vitraiden** [comment] 2019-01-05 17:20
If it's some sort of weird [heisenbug](https://en.wikipedia.org/wiki/Heisenbug) then I wouldn't worry about fixing it.  A rare client crash isn't going to bother me much.

**Comment by Pyrofab** [comment] 2019-08-27 16:22
Theoretically fixed in Requiem

**Closed by Pyrofab** 2019-08-27 16:22 UTC
Labels: bug, mod interaction
