### ISSUE TITLE
Incompatibility with 2 mods

### ISSUE THREAD

**Issue by Azvalk** [Ladysnake/Requiem#81] opened 2018-10-28 13:05 UTC
Hi :D
Do you know Player Revive ?
It has incompatibilities with Dissolution.

1 - In solo, if you open your game to LAN, if you die, the game crash.
2 - On a server, the game doesn't crash, Player Revive works..at 50%: the UI doesn't show up. 
You're stuck on the ground, waiting the end of the timer, then, Dissolution play his role.

So, I suggest the idea that Dissolution wait the real death of a player, after the timer of Player Revive, just before the death screen of Minecraft want to show up, to start his work, activate his blue shader ect.. 

Do You know Metamorph ?

Problem:
If the player is morphed, the model of the creature doesn't disapear.. not entierely..
Here is what happen with the morph of an Enderman in azombie, and the morph of a Golem in a skeleton..

![endermaninazombie](https://user-images.githubusercontent.com/37851897/47616236-6ea6d680-daba-11e8-81d8-8f56cd8fb98d.png)

![goleminaskeleton](https://user-images.githubusercontent.com/37851897/47616243-841c0080-daba-11e8-9633-8aebb607ad39.png)

**Comment by Pyrofab** [comment] 2018-10-28 13:07
The player revive issue has already been reported and should be fixed on their side.

**Comment by Azvalk** [comment] 2018-10-28 13:12
oh cool '-'
other thing..
a Golem in soul form, is very very slow.. 
It's like is moving in water, where he's very slow.
could the Soul Form.. I don't know, prevent metamorph behavior ?

**Comment by Pyrofab** [comment] 2018-10-28 13:13
Depends on how the mod is made. I guess I could force the player to revert to a human when in soul form.

**Comment by Azvalk** [comment] 2018-10-28 13:16
that would probably do the trick, but what about forcing the player to retake his morph shape when he is alive again ?

**Comment by Pyrofab** [comment] 2019-08-27 16:19
Metamorph is not on a supported version anymore, but the cause of the incompatibility is fixed in Requiem.

**Closed by Pyrofab** 2019-08-27 16:19 UTC
Labels: bug, feedback required, mod interaction
