### ISSUE TITLE
Zombie will attack itself after dissociation.

### ISSUE THREAD

**Issue by Touch-Night** [Ladysnake/Requiem#593] opened 2022-10-28 11:24 UTC
Zombie will attack itself after dissociation if you use its body to attack other zombies during possession. It' weird.

**Comment by Dunk0w0** [comment] 2022-10-28 16:46
i have noticed this too, it looked like it was getting attacked by something invisible because it had knockback but it attacking itself makes sense

**Comment by Touch-Night** [comment] 2022-10-29 03:22
Zombie will never attack itself in vanilla game. Not if you make a zombie hate another one somehow.

**Comment by Eman-3600** [comment] 2022-10-29 03:23
Have you tried it with other hostile mobs?

**Comment by Touch-Night** [comment] 2022-10-29 03:30
> Have you tried it with other hostile mobs?

Yes, it's not happen on skeleton and enderman. It seems that this issue only happen on zombie and zombie village.

**Comment by ruan128** [comment] 2022-12-19 17:30
it also happens with other zombies variants like husks if you attack another husk

**Comment by PsychoBreadstick** [comment] 2023-03-04 23:18
Seemingly fixed in a recent update.

**Closed as completed by PsychoBreadstick** 2023-03-04 23:18 UTC
Labels: bug, t:unreproduceable

**Comment by Pyrofab** [comment] 2023-03-04 23:37
Also duplicate of #476, and fixed for real in the upcoming MC 1.19.3 version
