### ISSUE TITLE
Requiem is incompatible with the latest backslots version due to locki

### ISSUE THREAD

**Issue by Givoric** [Ladysnake/Requiem#443] opened 2021-11-07 07:34 UTC
https://pastebin.com/eYBi2hnh

**Comment by Givoric** [comment] 2021-11-07 07:39
This is what the author of backslots has to say in regard:
https://github.com/Globox1997/BackSlot/issues/32

**Comment by Pyrofab** [comment] 2021-11-12 16:39
Closing as duplicate of #386

**Closed as completed by Pyrofab** 2021-11-12 16:39 UTC
Labels: bug, mod interaction
