### ISSUE TITLE
16.5 Silent Crash on instance launch standalone

### ISSUE THREAD

**Issue by ranenvious** [Ladysnake/Requiem#435] opened 2021-10-13 22:50 UTC
Description of issue : When I start the instance GDlauncher shows that it is loading its assets with the spinning icon but then the loading icon goes away, the "kill" command leaves the right click menu, and the game never opens. Correction : It does open, but only EXTREMELY briefly, I tried bringing up the game window during this time and it was white like it was in a not-responding state.

Information:
(Tested in standalone instance)
![image](https://user-images.githubusercontent.com/39103942/137222957-33ca2b5c-00e9-4ade-81a4-db4ca8d15ad6.png)
![image](https://user-images.githubusercontent.com/39103942/137222973-dd3efeb0-9886-4e89-b190-bfc2db145936.png)
![image](https://user-images.githubusercontent.com/39103942/137223008-d442416f-8e85-46a3-8665-ad74bd0c5722.png)
![image](https://user-images.githubusercontent.com/39103942/137223037-dcd73243-532d-406d-b1b5-83bb87466b27.png)
Instance creation : Created new fabric 16.5 instance with most recent version of fabric, installed requiem, waited for dependency to self install through GDlauncher.

Crashlog:
[crash-2021-10-13_18.43.28-client.txt](https://github.com/Ladysnake/Requiem/files/7341762/crash-2021-10-13_18.43.28-client.txt)

System information: 
[system.details.txt](https://github.com/Ladysnake/Requiem/files/7341765/system.details.txt)

additional info : After reading some other reports mentioning something called satin I tried adding that to the instance thinking maybe it was just lacking the dependency metadata but it didn't change anything.

**Comment by Pyrofab** [comment] 2021-10-14 13:23
Thanks for the detailed report ! Could you try a previous version maybe ?

**Comment by ranenvious** [comment] 2021-10-15 17:53
> Thanks for the detailed report ! Could you try a previous version maybe ?

(using the same 1.16.5 instance I used a screenshot of in my report with only the version of this mod changing)
1.7.10 - similar issue as latest
1.7.5 - opens a full sized MC window before crashing, unlike the smaller one generated by future versions
1.7.1 - window appears to open on task bar, but cannot be visually rendered before it crashes. (i.e. it only seems to exist on the taskbar, not on the screen)
1.6.3 - same as 1.7.1
1.6.1 - loads, but does not appear to actually do anything in game.
1.5.0 - crashes the same as 1.7.10
1.6.1 retest - crashes the same as 1.7.10 (no clue why it worked the first time but didn't actually load, maybe GDlauncher was throwing a fit or something)
logs : 
(I did several tests before this so and one test after it to verify something so I am attaching the logs that seems correct, but its hard to tell with how little actually got logged)


[2021-10-15-1.log.gz](https://github.com/Ladysnake/Requiem/files/7355146/2021-10-15-1.log.gz)
[2021-10-15-2.log.gz](https://github.com/Ladysnake/Requiem/files/7355147/2021-10-15-2.log.gz)
[2021-10-15-3.log.gz](https://github.com/Ladysnake/Requiem/files/7355148/2021-10-15-3.log.gz)
[2021-10-15-4.log.gz](https://github.com/Ladysnake/Requiem/files/7355150/2021-10-15-4.log.gz)
[2021-10-15-5.log.gz](https://github.com/Ladysnake/Requiem/files/7355151/2021-10-15-5.log.gz)
[2021-10-15-6.log.gz](https://github.com/Ladysnake/Requiem/files/7355152/2021-10-15-6.log.gz)
[2021-10-13-2.log.gz](https://github.com/Ladysnake/Requiem/files/7355153/2021-10-13-2.log.gz)

**Comment by Pyrofab** [comment] 2021-10-15 18:11
Oh wait, I think I know. Could you try latest requiem with Fabric Loader 0.11 or earlier ?

**Comment by ranenvious** [comment] 2021-10-15 22:05
On Fabric .11 standalone it loaded and worked fine. Do you need the log for this run as well or do you know what the issue is?

**Comment by Pyrofab** [comment] 2021-10-15 22:07
No need for the log, the issue is the mixin update that came with the new loader. That said, to properly fix it we'd have to release a new MC1.16.5 patch specifically for the new loader, but we are kinda focused on finishing the 2.0 update right now :/

**Comment by ranenvious** [comment] 2021-10-15 22:46
Ok, I guess I'll just see if the rest of my mods are compatible with .11. Will update 2.0 be coming to 16.5? If so then maybe you could include the patch in the release of that?

**Comment by Pyrofab** [comment] 2021-11-12 16:46
Should be fixed in Fabric Loader 0.12.4 and up

**Closed as completed by Pyrofab** 2021-11-12 16:46 UTC
