### ISSUE TITLE
Crash at launch with Identity

### ISSUE THREAD

**Issue by Tanden22** [Ladysnake/Requiem#193] opened 2020-10-31 19:33 UTC
Hiya,
I've got this weird crash whenever i launch Minecraft. The only thing i can get from the logs is that it's a problem with a "throwable" and "soulSneakingEyeHeight" from this mod. Any ideas?

I've included the log.
[latest.log](https://github.com/Ladysnake/Requiem/files/5469692/latest.log)

**Comment by Tanden22** [comment] 2020-10-31 20:23
I seem to have figured out the problem.
The Identity Mod [https://www.curseforge.com/minecraft/mc-mods/identity](url) causes a crash, which isn't too surprising considering what these two mods do.

**Comment by Pyrofab** [comment] 2020-10-31 20:27
That issue is caused by Identity, but it's definitely avoidable. Hopefully they can get a fix soon.

**Comment by Pyrofab** [comment] 2020-11-16 07:09
This issue should be fixed in identity's latest update. Thanks for the report !

**Closed by Pyrofab** 2020-11-16 07:09 UTC
Labels: bug, mod interaction
