### ISSUE TITLE
Can't cure myself

### ISSUE THREAD

**Issue by casualdegenerate** [Ladysnake/Requiem#551] opened 2022-07-27 23:01 UTC
I'm using a weakness potion, then eating an apple. It seems to just give me the apple's buffs, but not strength. And waiting the duration will do nothing. I was a wither skeleton while doing it btw :v but I'm pretty sure it applied to any mob I am. 
[Minecraft Log.txt](https://github.com/Ladysnake/Requiem/files/9204076/log.txt)
This was my mods list.
`3dskinlayers-fabric-1.4.6-mc1.18.2`, `appleskin-fabric-mc1.18.2-2.4.0`, `appliedenergistics2-11.1.4`, `architectury-4.6.77-fabric`, `Archive`, `artifacts-7.0.3+fabric`, `bclib-1.4.7`, `better-end-1.1.1`, `BetterVillage-Fabric-1.18.2-1.0.2`, `carpet-fixes-1.18.x-1.7.6+v220420 (1)`, `carpet-tis-addition-mc1.18.2-v1.33.0`, `clientcommands-2.6.6`, `cloth-api-3.2.64`, `cloth-config-6.2.62-forge`, `cmdkeybind-1.5.4-1.18`, `collective-fabric-1.18.x-4.27`, `continuity-1.1.0+1.18.2`, `Croptopia-1.18.2-FABRIC-2.0.5`, `DimensionalDoors-4.0.4-1.18.2`, `dropfullcarts-1.0.1`, `ecologics-fabric-1.18.2-1.7.3`, `Essential Dependencies`, `essential-client-1.18.2-1.1.6`, `Essential-fabric_1-18`, `extra-generators-1.2.1-BETA+1.18`, `extraalchemy-fabric-1.18.2-1.8.1`, `fabric-api-0.51.1+1.18.2`, `fabric-api-0.57.0+1.18.2`, `fabric-carpet-1.18.2-1.4.69+v220331`, `fabric-furnaces-2.1.1-1.18.2`, `fabric-language-kotlin-1.7.3+kotlin.1.6.20`, `feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1`, `guard-villagers-fabric-1.18.2-1.0.14`, `incantationem-1.1.3+1.18.2`, `indium-1.0.3+mc1.18.2`, `indium-1.0.6+mc1.18.2`, `infusion-table-mod-1.1.0`, `iris-mc1.18.2-1.2.4-build.38`, `iris-mc1.18.2-1.2.5`, `ironchests-2.0.3-fabric`, `isometric-renders-0.2.12+1.18`, `itemscroller-fabric-1.18.2-craftfix-1.2.6`, `journeymap-1.18.2-5.8.5-fabric`, `LibraryFerret-Fabric-1.18.2-2.0.0`, `light-overlay-6.0.5`, `litematica-fabric-1.18.2-0.11.1`, `local-server-entity-id-fix-1.0.0`, `malilib-fabric-1.18.2-0.12.1`, `minihud-fabric-1.18.2-0.22.0`, `modmenu-3.2.1`, `morevillagers-fabric-1.18.2-3.3.2`, `mostructures-1.4.2+1.18.2`, `MouseTweaks-fabric-mc1.18-2.22`, `NaturesCompass-1.18.2-2.0.3-fabric`, `notenoughcrashes-4.1.6+1.18.2-fabric`, `Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.2`, `OreTree-Fabric-1.18.2-0.2.4`, `pistorder-mc1.18.2-v1.5.0-fabric`, `repurposed_structures_fabric-4.1.14+1.18.2`, `requiem-2.0.0-beta.9`, `RoughlyEnoughItems-8.3.510`, `sodium-fabric-mc1.18.2-0.4.1+build.15`, `syncmatica-1.18.2-0.3.2`, `TerraBlender-fabric-1.18.2-1.1.0.102`, `totw_additions-1.2.1-1.18.2-fabric-polymer`, `treeharvester-fabric_1.18.x-5.1`, `trinkets-3.3.1`, `tweakermore-mc1.18.2-v3.0.0`, `tweakeroo-fabric-1.18.2-0.13.1`, `tweakfork-fabric-1.18.2-1.2.3`, `veinmining-fabric-0.0.13-1.18.2`, `viafabric-0.4.6+266-main`, `worldedit-mod-7.2.10`, `wraith-waystones-2.5.5+mc1.18.2`

**Comment by Pyrofab** [comment] 2022-07-27 23:44
Duplicate of #513 
Known issue, this is an incompatibility with the Collective library.

**Closed as completed by Pyrofab** 2022-07-27 23:44 UTC
Labels: bug, mod interaction
