### ISSUE TITLE
Movement become very fast when Origins installed

### ISSUE THREAD

**Issue by Touch-Night** [Ladysnake/Requiem#529] opened 2022-06-21 10:08 UTC
server mods list:
fabric-api-0.56.1+1.18.2
Origins-1.18.2-1.4.1
requiem-2.0.0-beta.8
requiem-pandemonium-2.0.0-beta.8

If possess a mob that isn't in water, movement speed become extremely fast in water. Also, if possess a mob that is originally in water, the problem disappear.

**Comment by Asteroid4** [comment] 2022-06-24 17:40
What if you use the human origin? it should have no effect.

**Comment by Eman-3600** [comment] 2022-06-26 02:50
The glitch is present no matter your origin.

**Comment by USMP-lancer** [comment] 2022-07-10 03:30
issue still present on beta 9, its very funny, but also kinda game breaking

**Comment by Pyrofab** [comment] 2022-07-19 09:37
Thanks for the report, should be fixed in the latest beta.

**Closed as completed by Pyrofab** 2022-07-19 09:37 UTC
Labels: bug, mod interaction

**Comment by Pyrofab** [comment] 2022-07-19 09:40
Duplicate of #514 by the way
