### ISSUE TITLE
Eating while processing mobs does not restore health 

### ISSUE THREAD

**Issue by Fade-Alchemist** [Ladysnake/Requiem#503] opened 2022-03-19 21:22 UTC
Eating while processing mobs does not restore health

**Comment by Noxalas** [comment] 2022-03-26 20:26
I had this issue while making a modpack and managed to isolate this to the Collective library by Serilum. Not sure what's causing it, but hopefully this helps.

Only installing Requiem and Collective is enough to recreate the bug. While posessing a zombie it is impossible to regenerate health by consuming raw meat and rotten flesh.

Minecraft version: 1.18.1
Requiem: 2.0.0 beta 7
Collective: 1.18.x 4.9

**Comment by rwmb** [comment] 2022-06-13 18:32
Another problem going on right now is that you can't cure yourself with weakness and golden apple, which is a shame since this mod is widely used in fabric modpacks...

**Comment by Fade-Alchemist** [comment] 2022-06-14 19:38
If you install the dark rites addon you can cure yourself with the cleansing ritual. The only thing keeping this mod playable atm. (only works for 1.18.1 and lower, Dark Rites 2 does not exist for 1.18.2)

**Comment by Eman-3600** [comment] 2022-06-15 19:46
Is this a 1.18.1 issue or a 1.18.2 issue (or both)?

**Comment by rwmb** [comment] 2022-06-16 17:36
> Is this a 1.18.1 issue or a 1.18.2 issue (or both)?

I've reproduced it in 1.18.2

**Comment by Fade-Alchemist** [comment] 2022-06-17 23:32
I had the issue in 1.18.1 ....just updated my server to 1.18.2 I was hoping it had been corrected there. not sure yet. I will let you know when I test.

**Comment by Pyrofab** [comment] 2022-07-19 12:47
Duplicate of #513 

This should be fixed in the latest beta.

**Closed as completed by Pyrofab** 2022-07-19 12:47 UTC
Labels: bug, mod interaction
