### ISSUE TITLE
Unpossessed animals move their legs too fast when Requiem is installed.

### ISSUE THREAD

**Issue by Igrium** [Ladysnake/Requiem#538] opened 2022-07-16 23:03 UTC
## Description:
A large percentage of Minecraft's mob entities move their legs (and whatever else is controlled by `EntityModel#setAngles()`) too fast. This is likely due to a mixin into Minecraft's entity rendering code causing this method to be called improperly. It has been shown to happen when Requiem and only Requiem is installed.

## Steps to reproduce:
Load a world with Requiem and look at an animal.

## Examples:

https://user-images.githubusercontent.com/34262244/179374405-c9bfdfff-f42a-42a4-ae04-4c1124cc18df.mp4

With a custom entity:

https://user-images.githubusercontent.com/34262244/179374439-dd4631d2-a055-47e6-98bb-0723ed577718.mp4

**Comment by Igrium** [comment] 2022-07-16 23:38
I would double check when code paths that call `LivingEntity#updateLimbs()` are called. That method is coded in such a way that calling it twice in one tick will result in the limbs moving twice the amount.

**Comment by Touch-Night** [comment] 2022-07-17 01:29
Oh I didn't even notice the problem

**Comment by Pyrofab** [comment] 2022-07-19 09:36
Good catch ! This should be fixed in the latest beta.

**Closed as completed by Pyrofab** 2022-07-19 09:36 UTC
Labels: bug, rendering

**Comment by Pyrofab** [comment] 2022-07-19 13:58
Actually, this is also a duplicate of #314 🙃
