### ISSUE TITLE
Better Portals minor visual issue

### ISSUE THREAD

**Issue by DarianLStephens** [Ladysnake/Requiem#131] opened 2019-06-03 00:03 UTC
When travelling to the Nether, you get a criss-cross pattern on the block highlight box, but only certain sides. After returning to the Overworld, as long as the portal remains in view, the background fog turns blue, and there's a black line along the border between the sky and horizon.
Turning away from the portal and back seems to fix it until you travel again.

**Comment by Pyrofab** [comment] 2019-06-03 06:39
In what circumstances does that happen ? Always ? As a soul ? As a mob ? If the latter, does it happen with spectator mode ?

**Comment by DarianLStephens** [comment] 2019-06-03 09:25
It happens as a normal player in creative mode, even after disabling shaders in your config.
So, I would guess always.

**Comment by Johni0702** [comment] 2019-06-04 18:57
Just FYI, there was an issue in the rendering of portal entities which leaves the alpha gl state disabled. I'm not at all familiar with Requiem but at least some of the rendering issues you're describing sound like they might be caused by that bug.
Though I see little connection to using the portal. Just wanted to make sure you're not wasting time on issues which have already been fixed.

The bug is fixed on `master` but no release has been made since the fix (will land in 0.1.5).

**Closed** 2019-10-13 18:53 UTC
Labels: bug, mod interaction
