### ISSUE TITLE
Origin's and requiem causes a datapack issue.

### ISSUE THREAD

**Issue by netcore10** [Ladysnake/Requiem#573] opened 2022-08-24 15:44 UTC
You sent me to them, they sent me to you a while ago. I waited just in case it was on their end, but i'm kinda confused.
https://mclo.gs/CfksJ3s

origins alone works fine,
requiem on it's own works fine, but i'm a bit at a loss now.

**Comment by Pyrofab** [comment] 2022-09-07 09:49
Closing this as a duplicate of #571

**Closed as not planned by Pyrofab** 2022-09-07 09:49 UTC
