### ISSUE TITLE
My world crashes (1.16.5)

### ISSUE THREAD

**Issue by Ameliaplayz** [Ladysnake/Requiem#368] opened 2021-06-30 09:15 UTC
So i was playing minecraft normally but then my world crashes, thankfully i have a mod named not enough crashes, it says that cardinal components api crashed the game, when i looked into the crash report, it says "Description: Ticking entity" and "type requiem:movement_alterer", this also happens when i die and possess a mob, here's the crash report, https://hastebin.com/sanerodilo.yaml

**Comment by Pyrofab** [comment] 2021-07-01 09:50
Oh, right. This has been reported in #360, it happens when a sprinting cat touches water.

**Comment by Pyrofab** [comment] 2021-07-01 09:50
Closing as duplicate of #360.

**Closed as completed by Pyrofab** 2021-07-01 09:50 UTC
