### ISSUE TITLE
Crash on Possesion (1.17.1 v2.0.0-alpha. 10)

### ISSUE THREAD

**Issue by ayellowlizard** [Ladysnake/Requiem#399] opened 2021-08-24 00:16 UTC
Hello. Whenever I possess a normal possessable mob on my server (Skeletons, Golems, etc.) I crash a few seconds after posessing it. I get the items from that mob (I get a bow and 4 arrows when skeleton) but then I crash after that.
I have pandemonium installed, but when I try to possess a pandemonium mob (Axolotls, Sheep, Etc.) I get the possession zoom and then immediately exit possession. I do not get the items and I do not get to control the mob.
After I boot up the game again and join the server, I crash a few seconds after joining. I'm stuck in this state unless somebody changes my origin, so please fix this. This is the same for (most) of the other members, too.
Here is my modpack that I use: https://www.dropbox.com/sh/8z81f2soo0pkfem/AADumJH5XEMvXB336lhnCizVa?dl=1
And here is the crash report: 
[crash-2021-08-24_10.51.11-client.txt](https://github.com/Ladysnake/Requiem/files/7035567/crash-2021-08-24_10.51.11-client.txt)

**Comment by Pyrofab** [comment] 2021-08-25 18:49
Duplicate of #398

**Closed as completed by Pyrofab** 2021-08-25 18:49 UTC
Labels: duplicate
