### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by ayzick** [Ladysnake/Requiem#264] opened 2021-03-29 21:41 UTC
It crashes on startup and dont know how to fix

**Comment by Pyrofab** [comment] 2021-03-29 21:49
Do you have optifine by any chance ?

**Comment by ayzick** [comment] 2021-03-29 23:50
yes

**Comment by Pyrofab** [comment] 2021-03-30 11:27
There's your issue then, this is a duplicate of #262

**Closed as completed by Pyrofab** 2021-03-30 11:27 UTC
